### ISSUE TITLE
Javascript transform : select function to process items

### ISSUE THREAD

**Issue by jasonm23** [cutbox/CutBox#60]
## Feature Description - Javascript transform : select function to process items

[Gherkin DSL](https://github.com/cucumber/cucumber/wiki/Given-When-Then) / [BDD: Given/When/Then](https://sites.google.com/site/unclebobconsultingllc/the-truth-about-bdd)

> **GIVEN** I have a properly configured* javascript at `~/.cutbox.js`
> **WHEN** I press <kbd>Cmd</kbd> + <kbd>Enter</kbd>
> **THEN** I can pick a named function from a list of registered functions
> **AND** it will process items and paste the result

### Tasks

- [x] *define specification of properly configured javascript
- [x] UI show list of named functions
- [x] UI for picking function
- [x] use selected function to process items and paste

If you would like this feature add your vote with reaction - :+1: or :-1:

- - -

**Comment by jasonm23** [comment]
# Registering functions

Add each function to a register, with a name, and possibly other meta data in future (shortcut key etc.)

```javascript
var myFunc = (i) => i.map( e => e )

functions: [
  { name: "My inline function", func: i => i.map( e => e ) },
  { name: "My function by reference", func: myFunc } 
]
```

**Comment by jasonm23** [comment]
Use map or join functions and compose pipes with them
